# Generated by Django 3.1.7 on 2021-04-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Назавние')),
                ('breadcrumbs', models.ImageField(upload_to='portfolio', verbose_name='Хлебные крошки (картинка)')),
                ('price', models.CharField(max_length=150, verbose_name='Цена')),
                ('date', models.DateField(verbose_name='Дата окончания проекта')),
                ('adress', models.CharField(max_length=250, verbose_name='Адрес объекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('meta_title', models.CharField(max_length=100, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.CharField(max_length=280, null=True, verbose_name='Мета описание')),
                ('meta_keywords', models.CharField(max_length=200, null=True, verbose_name='Ключевые слова')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
        migrations.CreateModel(
            name='Serv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назавние услуги')),
                ('image_prew', models.ImageField(upload_to='serv', verbose_name='Основное изображение')),
                ('description', models.CharField(max_length=300, verbose_name='Короткое описание')),
                ('text', models.TextField(verbose_name='Описание')),
                ('meta_title', models.CharField(max_length=100, verbose_name='Мета заголовок')),
                ('meta_description', models.CharField(max_length=280, verbose_name='Мета описание')),
                ('meta_keywords', models.CharField(max_length=200, verbose_name='Ключевые слова')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('image', models.ImageField(null=True, upload_to='sliders', verbose_name='Изображение')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider', to='serv.serv', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
        migrations.CreateModel(
            name='ServImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Описание картинки')),
                ('image', models.ImageField(upload_to='servimage', verbose_name='Изображение')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='serv.serv', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Фото в услугах',
                'verbose_name_plural': 'Фото в услугах',
            },
        ),
        migrations.CreateModel(
            name='ServChildren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назавние')),
                ('image', models.ImageField(upload_to='servsildren')),
                ('text', models.TextField(verbose_name='Описание')),
                ('meta_title', models.CharField(max_length=100, verbose_name='Мета заголовок')),
                ('meta_description', models.CharField(max_length=280, verbose_name='Мета описание')),
                ('meta_keywords', models.CharField(max_length=200, verbose_name='Ключевые слова')),
                ('slug', models.SlugField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='serv.serv', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вложенная категория',
                'verbose_name_plural': 'Вложенные категории',
            },
        ),
        migrations.CreateModel(
            name='PortfolioProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назавние')),
                ('value', models.CharField(max_length=150, verbose_name='Значение')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='serv.portfolio', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='serv.portfolio', verbose_name='Изображение')),
            ],
        ),
    ]
