# Generated by Django 3.1.7 on 2021-04-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='portfolioproperty',
            options={'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.RenameField(
            model_name='portfolioproperty',
            old_name='value',
            new_name='data',
        ),
    ]
