# Generated by Django 3.1.7 on 2021-05-13 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0003_auto_20210412_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='serv',
            name='breadcrumbs',
            field=models.ImageField(blank=True, null=True, upload_to='serv'),
        ),
        migrations.AddField(
            model_name='serv',
            name='h1',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок H1'),
        ),
        migrations.AddField(
            model_name='servchildren',
            name='breadcrumbs',
            field=models.ImageField(blank=True, null=True, upload_to='serv'),
        ),
        migrations.AddField(
            model_name='servchildren',
            name='h1',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок H1'),
        ),
        migrations.CreateModel(
            name='ServChildrenBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст блока')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет фона')),
                ('text_color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет текста')),
                ('bg', models.ImageField(blank=True, null=True, upload_to='remontblock', verbose_name='Фон')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block', to='serv.servchildren', verbose_name='блок')),
            ],
            options={
                'verbose_name': 'Дополнительный блок',
                'verbose_name_plural': 'Дополнительные блоки',
            },
        ),
        migrations.CreateModel(
            name='ServBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст блока')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет фона')),
                ('text_color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет текста')),
                ('bg', models.ImageField(blank=True, null=True, upload_to='remontblock', verbose_name='Фон')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block', to='serv.serv', verbose_name='цвет')),
            ],
            options={
                'verbose_name': 'Дополнительный блок',
                'verbose_name_plural': 'Дополнительные блоки',
            },
        ),
    ]
