# Generated by Django 3.1.7 on 2021-05-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0004_auto_20210513_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='servblock',
            name='button',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='servchildrenblock',
            name='button',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Текст кнопки'),
        ),
    ]
