# Generated by Django 3.1.7 on 2021-05-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Обратный звонок', 'verbose_name_plural': 'Обратный звонок'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='contact',
            name='theme',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тема сообщения'),
        ),
    ]
