# Generated by Django 3.1.7 on 2021-05-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20210521_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPopup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('tel', models.CharField(max_length=20, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Контакты попап',
                'verbose_name_plural': 'Контакты попап',
            },
        ),
    ]
