# Generated by Django 3.1.7 on 2021-05-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_contactpopup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('tel', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('theme', models.CharField(max_length=100, verbose_name='Тема сообщения')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявки со страницы контктов',
                'verbose_name_plural': 'Заявки со страницы контктов',
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='theme',
        ),
    ]
