# Generated by Django 3.1.7 on 2021-05-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20210521_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactfull',
            old_name='email',
            new_name='email_2',
        ),
        migrations.RenameField(
            model_name='contactfull',
            old_name='message',
            new_name='message_2',
        ),
        migrations.RenameField(
            model_name='contactfull',
            old_name='name',
            new_name='name_2',
        ),
        migrations.RenameField(
            model_name='contactfull',
            old_name='tel',
            new_name='tel_2',
        ),
        migrations.RenameField(
            model_name='contactfull',
            old_name='theme',
            new_name='theme_2',
        ),
    ]
