# Generated by Django 3.1.7 on 2021-05-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_auto_20210521_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactfull',
            old_name='date',
            new_name='date_2',
        ),
    ]
