# Generated by Django 3.1.7 on 2021-05-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20210521_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactfull',
            name='message_2',
            field=models.TextField(null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contactpopup',
            name='message',
            field=models.TextField(null=True, verbose_name='Сообщение'),
        ),
    ]
