# Generated by Django 3.1.7 on 2021-04-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breadcrumbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ImageField(upload_to='breadcrumbs', verbose_name='О нас')),
                ('service', models.ImageField(upload_to='breadcrumbs', verbose_name='Услуги')),
                ('contact', models.ImageField(upload_to='breadcrumbs', verbose_name='Контакты')),
                ('portfolio', models.ImageField(upload_to='breadcrumbs', verbose_name='Портфолио')),
                ('rewiew', models.ImageField(upload_to='breadcrumbs', verbose_name='Отзывы')),
                ('sale', models.ImageField(upload_to='breadcrumbs', verbose_name='Акции')),
            ],
            options={
                'verbose_name': 'Изображение для хлебных крошек',
                'verbose_name_plural': 'Изображения для хлебных крошек',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании')),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to='setup', verbose_name='Логотип')),
                ('logo_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текстовый логотип')),
                ('time', models.CharField(max_length=150, verbose_name='Время работы')),
                ('email', models.CharField(max_length=100, verbose_name='Почта')),
                ('map', models.TextField(blank=True, null=True, verbose_name='Код карты')),
            ],
            options={
                'verbose_name': 'Общая настройка сайта',
                'verbose_name_plural': 'Общие настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=200, verbose_name='Мета заголовок')),
                ('meta_description', models.CharField(max_length=350, verbose_name='Мета описание')),
                ('meta_subtitle', models.CharField(max_length=150, verbose_name='Вторая часть заголовка сайта (через | )')),
                ('meta_keywords', models.CharField(max_length=350, verbose_name='Ключевые слова')),
                ('domen', models.CharField(max_length=350, verbose_name='Полный адрес сайта')),
            ],
            options={
                'verbose_name': 'Мета настройка сайта',
                'verbose_name_plural': 'Мета настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=250, verbose_name='Иконка (fontawesome.com)')),
                ('link', models.CharField(max_length=100, verbose_name='Полная ссылка (с доменным именем)')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='myapp.config')),
            ],
            options={
                'verbose_name': 'Социальные сети',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Отображаемое название')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='myapp.config')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
    ]
