# Generated by Django 3.1.7 on 2021-05-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='sale')),
                ('text', models.TextField(verbose_name='Текст акции')),
                ('date', models.DateField(verbose_name='Дата окончания')),
                ('activate', models.BooleanField(verbose_name='Активость')),
                ('meta_title', models.CharField(max_length=100, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.CharField(max_length=280, null=True, verbose_name='Мета описание')),
                ('meta_keywords', models.CharField(max_length=200, null=True, verbose_name='Ключевые слова')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
